# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: server
output: internal/openapi/server/openapi_gen_server.go
generate:
  fiber-server: true
  strict-server: true
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
import-mapping:
  "./openapi_spec_components.yaml": oapi-codegen-example/internal/openapi/model
